apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-infra-ose0500g0001"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Gi
  nfs:
    path: /exports/lv_ose09
    server: aoappd-e-nfs001.ctho.asbn.gtwy.dcn
  persistentVolumeReclaimPolicy: Retain
